/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class FormTikerTravel extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTikerTravel.class.getName());

    /**
     * Creates new form FormTikerTravel
     */
    public FormTikerTravel() {
        initComponents();

        namaField.putClientProperty(
                "JTextField.placeholderText",
                "Nama Lengkap"
        );

        nomorHpField.putClientProperty(
                "JTextField.placeholderText",
                "contoh: 081234567890"
        );

        getRootPane().setDefaultButton(pesanButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelasGroup = new javax.swing.ButtonGroup();
        namaLabel = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        nomorHpLabel = new javax.swing.JLabel();
        nomorHpField = new javax.swing.JTextField();
        kotaTujuanLabel = new javax.swing.JLabel();
        kotaTujuanCombo = new javax.swing.JComboBox<>();
        kelasLabel = new javax.swing.JLabel();
        ekonomiRadio = new javax.swing.JRadioButton();
        bisnisRadio = new javax.swing.JRadioButton();
        eksekutifRadio = new javax.swing.JRadioButton();
        fasilitasLabel = new javax.swing.JLabel();
        bagasiCheck = new javax.swing.JCheckBox();
        makanCheck = new javax.swing.JCheckBox();
        asuransiCheck = new javax.swing.JCheckBox();
        catatanLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatanArea = new javax.swing.JTextArea();
        pesanButton = new javax.swing.JButton();
        temaToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemesanan Tiket Travel");

        namaLabel.setText("Nama Pemesan");

        nomorHpLabel.setText("Nomor HP");

        kotaTujuanLabel.setText("Kota Tujuan");

        kotaTujuanCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));

        kelasLabel.setText("Kelas");

        kelasGroup.add(ekonomiRadio);
        ekonomiRadio.setSelected(true);
        ekonomiRadio.setText("Ekonomi");

        kelasGroup.add(bisnisRadio);
        bisnisRadio.setText("Bisnis");

        kelasGroup.add(eksekutifRadio);
        eksekutifRadio.setText("Eksekutif");

        fasilitasLabel.setText("Fasilitas Tambahan");

        bagasiCheck.setText("Bagasi");

        makanCheck.setText("Makan");

        asuransiCheck.setText("Asuransi");

        catatanLabel.setText("Catatan");

        catatanArea.setColumns(20);
        catatanArea.setRows(3);
        jScrollPane1.setViewportView(catatanArea);

        pesanButton.setText("Pesan");
        pesanButton.addActionListener(this::pesanButtonActionPerformed);

        temaToggle.setText("Mode Gelap");
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(temaToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pesanButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaLabel)
                            .addComponent(nomorHpLabel)
                            .addComponent(kotaTujuanLabel)
                            .addComponent(kelasLabel)
                            .addComponent(fasilitasLabel)
                            .addComponent(catatanLabel))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bagasiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(makanCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(asuransiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eksekutifRadio)
                            .addComponent(bisnisRadio)
                            .addComponent(ekonomiRadio)
                            .addComponent(namaField)
                            .addComponent(nomorHpField)
                            .addComponent(kotaTujuanCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorHpLabel)
                    .addComponent(nomorHpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaTujuanLabel)
                    .addComponent(kotaTujuanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasLabel)
                    .addComponent(ekonomiRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bisnisRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eksekutifRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fasilitasLabel)
                    .addComponent(bagasiCheck)
                    .addComponent(makanCheck)
                    .addComponent(asuransiCheck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catatanLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesanButton)
                    .addComponent(temaToggle))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
        tampilkanRingkasan();
    }//GEN-LAST:event_pesanButtonActionPerformed

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed
        gantiTema(temaToggle.isSelected());
    }//GEN-LAST:event_temaToggleActionPerformed

    private void tampilkanRingkasan() {
        String kelas;

        if (ekonomiRadio.isSelected()) {
            kelas = "Ekonomi";
        } else if (bisnisRadio.isSelected()) {
            kelas = "Bisnis";
        } else {
            kelas = "Eksekutif";
        }

        String fasilitas = "";

        if (bagasiCheck.isSelected()) {
            fasilitas += "Bagasi";
        }

        if (makanCheck.isSelected()) {
            fasilitas += fasilitas.isEmpty() ? "Makan" : ", Makan";
        }

        if (asuransiCheck.isSelected()) {
            fasilitas += fasilitas.isEmpty() ? "Asuransi" : ", Asuransi";
        }

        if (fasilitas.isEmpty()) {
            fasilitas = "-";
        }

        String pesan
                = "Nama Pemesan: " + namaField.getText()
                + "\nNomor HP: " + nomorHpField.getText()
                + "\nKota Tujuan: " + kotaTujuanCombo.getSelectedItem()
                + "\nKelas: " + kelas
                + "\nFasilitas: " + fasilitas
                + "\nCatatan: " + catatanArea.getText();

        JOptionPane.showMessageDialog(
                this,
                pesan,
                "Ringkasan Pemesanan",
                JOptionPane.INFORMATION_MESSAGE
        );
    }

    private void gantiTema(boolean gelap) {

        if (gelap) {
            FlatDarkLaf.setup();
        } else {
            FlatLightLaf.setup();
        }

        FlatLaf.updateUI();

        temaToggle.setText(
                gelap ? "Mode Terang" : "Mode Gelap"
        );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTikerTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asuransiCheck;
    private javax.swing.JCheckBox bagasiCheck;
    private javax.swing.JRadioButton bisnisRadio;
    private javax.swing.JTextArea catatanArea;
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JRadioButton ekonomiRadio;
    private javax.swing.JRadioButton eksekutifRadio;
    private javax.swing.JLabel fasilitasLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup kelasGroup;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JComboBox<String> kotaTujuanCombo;
    private javax.swing.JLabel kotaTujuanLabel;
    private javax.swing.JCheckBox makanCheck;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField nomorHpField;
    private javax.swing.JLabel nomorHpLabel;
    private javax.swing.JButton pesanButton;
    private javax.swing.JToggleButton temaToggle;
    // End of variables declaration//GEN-END:variables
}
